from models import TestGenerationResult


def format_pr_comment(result: TestGenerationResult) -> str:
    lines = []
    lines.append("## AI-Suggested Test Cases")
    lines.append(f"**Experience ID:** `{result.experience_id}`")
    lines.append(f"**Changed Files:** {', '.join(f'`{f}`' for f in result.changed_files)}")
    lines.append(f"**Model:** `{result.generation_model}`")
    lines.append("")
    lines.append(result.summary)
    lines.append("")
    lines.append("> **Note:** These are AI-generated suggestions for human review. "
                 "They are not auto-committed. Adopt, adapt, or discard as appropriate.")
    lines.append("")

    for i, test in enumerate(result.suggested_tests, 1):
        priority_badge = {"high": "HIGH", "medium": "MEDIUM", "low": "LOW"}[test.priority]
        type_label = test.test_type.value.replace("_", " ").upper()
        lines.append(f"### [{priority_badge}] {i}. {test.name}")
        lines.append(f"**Type:** {type_label} | **Priority:** {test.priority}")
        lines.append(f"**Rationale:** {test.rationale}")
        lines.append("")
        lang = "javascript" if test.test_type.value == "performance" else "typescript"
        lines.append(f"```{lang}")
        lines.append(test.code)
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by AI Test Gen | Experience ID: {result.experience_id}*")
    return "\n".join(lines)
